services:
  # Serviço para o Host Frontend
  host-app:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: bytebank-host-app
    ports:
      - "4200:80"
    depends_on:
      - resume-account-mf

  # Serviço para o Microfrontend
  resume-account-mf:
    build:
      context: .
      dockerfile: Dockerfile.remoto
    container_name: bytebank-resume-account-mf

    ports:
      - "4201:80"

  # Serviço para Backend
  backend-api:
    build:
      context: /home/watermelon/Documentos/pessoal/bytebank-backend
      dockerfile: Dockerfile
    container_name: bytebank-backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo-db:27017/bytebank
      - JWT_SECRET=seu_super_segredo_aqui
    volumes:
      - /home/watermelon/Documentos/pessoal/bytebank-backend/uploads:/usr/src/app/uploads
    depends_on:
      - mongo-db

  # Serviço para o Banco de Dados
  mongo-db:
    image: mongo:latest
    container_name: bytebank-mongodb
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: